### ISSUE TITLE
Can I use TIDE on my own dataset - given coco-formatted Ground-Truth and predicted Bounding Boxes?

### ISSUE THREAD

**Issue by codingbutstillalive** [dbolya/tide#51]
I mean, I intuitively thought so. But then I read "The currently supported datasets are COCO, LVIS, Pascal, and Cityscapes. More details and documentation on how to write your own database drivers coming soon!". So I am wondering. I mean.. this shouldn't really be an issue.

**Comment by BenyunZhao** [comment]
hi, have you solved this problem?

**Comment by Michael-24** [comment]
Traceback (most recent call last):
  File "/home/gonglianghao/object_detection/ultralytics4.12/get_COCO_metrics.py", line 50, in <module>
    gt = datasets.COCO(annFile)
  File "/home/gonglianghao/miniconda3/envs/yolov8_new/lib/python3.9/site-packages/tidecv/datasets.py", line 102, in COCO
    mask   = f.toRLE(ann['segmentation'], image_lookup[image]['width'], image_lookup[image]['height'])
  File "/home/gonglianghao/miniconda3/envs/yolov8_new/lib/python3.9/site-packages/tidecv/functions.py", line 90, in toRLE
    rles = maskUtils.frPyObjects(mask, h, w)
  File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
IndexError: list index out of range
how can i fix this?
